language: node_js
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - CXX=g++-4.8
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
script: make test-cov
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
