language: node_js
node_js:
  - "0.10"
before_script:
  - mysql -e 'create database osmos'
  - sudo add-apt-repository ppa:rethinkdb/ppa
  - sudo apt-get update
  - sudo apt-get install rethinkdb
services:
  - mongodb
  - elasticsearch
