language: node_js
node_js:
  - "0.10"
before_script:
  - mysql -e 'create database osmos'
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb
services:
  - mongodb
  - elasticsearch
