language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"
before_script:
  - mysql -e 'create database osmos'
services:
  - mongodb
  - elasticsearch
script: make test-cov
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
