language: node_js
node_js:
  - "0.10"
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y  --force-yes
before_script:
  - mysql -e 'create database osmos'
  - sudo rethinkdb --daemon
  - ulimit -S -n 2048
  - sleep 10
services:
  - mongodb
  - elasticsearch
after_script:
  - killall rethinkdb
